### PR TITLE
An attempt to optimize controls

### PR DESCRIPTION
**Pull request by MemeHovy**

### CODE REVIEW

**Comment by mcagabe19** [comment]
discarding

**Comment by MemeHovy** [comment]
> discarding

why tf, I was just making progress

**Comment by mcagabe19** [comment]
> > discarding
> 
> why tf, I was just making progress

you can revert idk I just find out that makes even more lag and mostly issues

**Comment by MemeHovy** [comment]
> > > discarding
> > 
> > 
> > why tf, I was just making progress
> 
> you can revert idk I just find out that makes even more lag and mostly issues

good to know

**Pull request closed without merging**
