### PR TITLE
Optimization version

### PR DESCRIPTION
**Pull request by Hiho2950**
- optimized goodNoteHit
- optimized botplay too

i had try that so pls accept for helping some people

### CODE REVIEW

**Comment by MemeHovy** [comment]
@Karim-Akra you're gonna have to test this on android, but I'mma test this rq

**Comment by MemeHovy** [comment]
there's some things that need fixing which I'll do after the merge, like not having ratings disabled by default

**Comment by Karim-Akra** [comment]
Okay lemme download rq and test

**Comment by Karim-Akra** [comment]
It's kinda better i remember that the fps used to drop to 20-30 beffor but there is a glitch where all ratings are zeros

**Comment by Hiho2950** [comment]
tnx for the merge for me i had add an option to enable and disable the rating and combo and it s disabled automatically for the botplay

**Pull request merged**
