### PR TITLE
I think that will help to use .PsychEngine folder

### PR DESCRIPTION
**Pull request by Hiho2950**
i had add the optimization that i want to my fork if you want to add it use mine

### CODE REVIEW

**Comment by mcagabe19** [comment]
due android 11+ write and read issues we can't use .PsychEngine so I have to close

**Comment by Hiho2950** [comment]
> due android 11+ write and read issues we can't use .PsychEngine so I have to close

we can for me i can on psych build of other porters

**Comment by Hiho2950** [comment]
i had make a test when apk finish download i will tell you the results i have android 11

**Comment by Hiho2950** [comment]
the game crashes so idk anymore

**Comment by mcagabe19** [comment]
> i had make a test when apk finish download i will tell you the results i have android 11

I have 13

**Comment by Hiho2950** [comment]
it tells me to create one

**Comment by mcagabe19** [comment]
we already tried test .PsychEngine but we keep get errors at read and write

**Comment by Hiho2950** [comment]
> > i had make a test when apk finish download i will tell you the results i have android 11
> 
> I have 13

ok i will try to use other way to fix it if fixed i will tell you

**Comment by Hiho2950** [comment]
> we already tried test .PsychEngine but we keep get errors at read and write

ah idk why they had change the file managing system for android/data and android/obb unless if u use zarchiver with root

**Comment by Karim-Akra** [comment]
You can't use /.PsychEngine on Android 10 and above when the application SDK version is 29

If the sdk the version is 29 /.PsychEngine will work only on older android versions

**Comment by GhostL650** [comment]
> You can't use /.PsychEngine on Android 10 and above when the application SDK version is 29
> 
> If the sdk the version is 29 /.PsychEngine will work only on older android versions

Just use apk editor to change it to 28

**Comment by mcagabe19** [comment]
enough talking

**Pull request closed without merging**
